electrobin/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib.gis import admin
from django.shortcuts import redirect
from django.urls import reverse_lazy, path
from os import listdir

from apps.sensors.api import SensorListAPIView
from app.api import (
    ContainerListAPIView, CitiesListAPIView, MobileApiObtainAuthToken, UserProfile, MobileAppTranslationView,
    get_trashbin_auth_token, TrashbinDataView, TrashbinJobsView, GenericObtainAuthToken,
)
from apps.core.helpers import CompanyDeviceProfile
from apps.core.urls import account_urlpatterns
from apps.core.views import (
    create_top_level_static_view, TOP_LEVEL_STATIC_DIR, NotificationsFeedDataView, NotificationsListView,
    FollowNotificationView, MarkAllNotificationsReadView, NotificationsSettingsFormView, switch_language,
)
from app.views import (
    CityList, CityCreate, CityUpdate, CityDelete, CityDataView,
    CompanyList, CompanyCreate, CompaniesDataView, CompanyUpdate, CompanyDelete, CompanyUserList,
    UserList, UserCreate, UsersDataView, UserDelete, UserUpdate,
    ContainerList, ContainerCreate, ContainersDataView, ContainerMapCard, ContainerDelete, ContainerUpdate,
    ContainerDetail,
    SectorList, SectorCreate, SectorsDataView, SectorUpdate, SectorDelete,
    RoutesList, RoutesDataView, RouteAbort, RouteDetail, RouteResend,
    DriversList, DriversDataView, DriverDetail,
    DriverUnavailabilityPeriodCreate, DriverUnavailabilityPeriodUpdate, DriverUnavailabilityPeriodDelete,
)
from apps.sensors.views import (
    SensorsListView, SensorsDataView, SensorUpdateView, SensorMapCard, CreateRouteView as SensorCreateRouteView,
    OnboardSensorView,
)
from apps.trashbins.views import CreateRouteView as TrashbinCreateRouteView, TrashbinFullnessForecastView
from apps.main.helpers import get_effective_company_device_profile
from apps.main.views import settings_index, invalid_license_view, account_info_view, extend_license_view
from views.report_simbalance import report_simbalance, SimBalanceReportList
# from views.report_traffic import *
from views.report_pressure import report_pressure, PressureReportList, PressureReportStackedChart
from views.report_humidity import report_humidity, HumidityReportList, HumidityReportStackedChart
from views.report_air_quality import report_air_quality, AirQualityReportList, AirQualityReportStackedChart

from apps.trashbins.reports.fullness import (
    report_fullness as trashbin_report_fullness,
    FullnessReportList as TrashbinFullnessReportList,
    FullnessReportStackedChart as TrashbinFullnessReportStackedChart,
)
from apps.trashbins.reports.battery_level import (
    report_battery_level as trashbin_report_battery_level,
    BatteryLevelReportList as TrashbinBatteryLevelReportList,
    BatteryLevelReportStackedChart as TrashbinBatteryLevelReportStackedChart,
)
from apps.trashbins.reports.errors import (
    report_errors as trashbin_report_errors,
    ErrorsReportList as TrashbinErrorsReportList,
    ErrorsReportPieChart as TrashbinErrorsReportPieChart,
)
from apps.trashbins.reports.temperature import (
    report_temperature as trashbin_report_temperature,
    TemperatureReportList as TrashbinTemperatureReportList,
    TemperatureReportStackedChart as TrashbinTemperatureReportStackedChart,
)
from apps.trashbins.reports.collection import (
    report_collection as trashbin_report_collection,
    CollectionReportList as TrashbinCollectionReportList,
    CollectionReportErrorsPieChart as TrashbinCollectionReportErrorsPieChart,
    CollectionReportFullnessPieChart as TrashbinCollectionReportFullnessPieChart,
    CollectionReportTypesPieChart as TrashbinCollectionReportWasteTypesPieChart,
    CollectionReportSectorsPieChart as TrashbinCollectionReportSectorsPieChart,
)

from apps.sensors.reports.fullness import (
    report_fullness as sensor_report_fullness,
    FullnessReportList as SensorFullnessReportList,
    FullnessReportStackedChart as SensorFullnessReportStackedChart,
)
from apps.sensors.reports.battery_level import (
    report_battery_level as sensor_report_battery_level,
    BatteryLevelReportList as SensorBatteryLevelReportList,
    BatteryLevelReportStackedChart as SensorBatteryLevelReportStackedChart,
)
from apps.sensors.reports.errors import (
    report_errors as sensor_report_errors,
    ErrorsReportList as SensorErrorsReportList,
    ErrorsReportPieChart as SensorErrorsReportPieChart,
)
from apps.sensors.reports.temperature import (
    report_temperature as sensor_report_temperature,
    TemperatureReportList as SensorTemperatureReportList,
    TemperatureReportStackedChart as SensorTemperatureReportStackedChart,
)
from apps.sensors.reports.collection import (
    report_collection as sensor_report_collection,
    CollectionReportList as SensorCollectionReportList,
    CollectionReportWasteTypesPieChart as SensorCollectionReportWasteTypesPieChart,
    CollectionReportSectorsPieChart as SensorCollectionReportSectorsPieChart,
)

from apps.main.reports.track import report_track, TrackReportList


api_urlpatterns = [
    url(r'^containers/$', ContainerListAPIView.as_view()),
    url(r'^cities/(?P<pk>\d+)/$', CitiesListAPIView.as_view()),
    url(r'^mobile/auth-token/', MobileApiObtainAuthToken.as_view()),
    url(r'^mobile/profile/$', UserProfile.as_view()),
    url(r'^mobile/language/$', MobileAppTranslationView.as_view()),
    url(r'^trashbin/get-token/', get_trashbin_auth_token),
    url(r'^trashbin/data/', TrashbinDataView.as_view()),
    url(r'^trashbin/jobs/', TrashbinJobsView.as_view()),
    url(r'^sensors/$', SensorListAPIView.as_view()),
    url(r'^get-auth-token/', GenericObtainAuthToken.as_view(), name='api-get-token'),
    url(r'^$', lambda r: redirect(reverse_lazy('api-get-token')), name='api-root'),
]

cities_urlpatterns = ([
    url(r'^$', CityList.as_view(), name='list'),
    url(r'^create/$', CityCreate.as_view(), name='create'),
    url(r'^data/$', CityDataView.as_view(), name='data'),
    url(r'^(?P<pk>\d+)/update/$', CityUpdate.as_view(), name='update'),
    url(r'^(?P<pk>\d+)/delete/$', CityDelete.as_view(), name='delete'),
], 'cities')

company_urlpatterns = ([
    url(r'^$', CompanyList.as_view(), name='list'),
    url(r'^add/$', CompanyCreate.as_view(), name='add'),
    url(r'^data/$', CompaniesDataView.as_view(), name='data'),
    url(r'(?P<pk>\d+)/delete/$', CompanyDelete.as_view(), name='delete'),
    url(r'(?P<pk>\d+)/update/$', CompanyUpdate.as_view(), name='update'),
    url(r'(?P<pk>\d+)/users/$', CompanyUserList.as_view(), name='users'),
], 'companies')

user_urlpatterns = ([
    url(r'^$', UserList.as_view(), name='list'),
    url(r'^create/$', UserCreate.as_view(), name='create'),
    url(r'^data/$', UsersDataView.as_view(), name='data'),
    url(r'^(?P<pk>\d+)/delete/$', UserDelete.as_view(), name='delete'),
    url(r'^(?P<pk>\d+)/update/$', UserUpdate.as_view(), name='update'),
], 'users')

container_urlpatterns = ([
    url(r'^$', ContainerList.as_view(), name='list'),
    url(r'^create/$', ContainerCreate.as_view(), name='create'),
    url(r'^data/$', ContainersDataView.as_view(), name='data'),
    url(r'^map/$', ContainerListAPIView.as_view(), name='map'),
    url(r'^(?P<pk>\d+)/$', ContainerDetail.as_view(), name='detail'),
    url(r'^(?P<pk>\d+)/map-card/$', ContainerMapCard.as_view(), name='map-card'),
    url(r'^(?P<pk>\d+)/delete/$', ContainerDelete.as_view(), name='delete'),
    url(r'^(?P<pk>\d+)/update/$', ContainerUpdate.as_view(), name='update'),
], 'containers')

sector_urlpatterns = ([
    url(r'^$', SectorList.as_view(), name='list'),
    url(r'^create/$', SectorCreate.as_view(), name='create'),
    url(r'^data/$', SectorsDataView.as_view(), name='data'),
    url(r'^(?P<pk>\d+)/update/$', SectorUpdate.as_view(), name='update'),
    url(r'^(?P<pk>\d+)/delete/$', SectorDelete.as_view(), name='delete'),
], 'sectors')

trashbin_reports_urlpatterns = ([
    path('fullness/', trashbin_report_fullness, name='fullness'),
    path('fullness/table-data/', TrashbinFullnessReportList.as_view(), name='fullness_table_data'),
    path('fullness/chart-data/', TrashbinFullnessReportStackedChart.as_view(), name='fullness_chart_data'),

    path('battery-level/', trashbin_report_battery_level, name='battery_level'),
    path('battery-level/table-data/', TrashbinBatteryLevelReportList.as_view(), name='battery_level_table_data'),
    path('battery-level/chart-data/', TrashbinBatteryLevelReportStackedChart.as_view(),
         name='battery_level_chart_data'),

    path('errors/', trashbin_report_errors, name='errors'),
    path('errors/table-data/', TrashbinErrorsReportList.as_view(), name='errors_table_data'),
    path('errors/chart-data/', TrashbinErrorsReportPieChart.as_view(), name='errors_chart_data'),

    path('temperature/', trashbin_report_temperature, name='temperature'),
    path('temperature/table-data/', TrashbinTemperatureReportList.as_view(), name='temperature_table_data'),
    path('temperature/chart-data/', TrashbinTemperatureReportStackedChart.as_view(), name='temperature_chart_data'),

    path('collection/', trashbin_report_collection, name='collection'),
    path('collection/table-data/', TrashbinCollectionReportList.as_view(), name='collection_table_data'),
    path('collection/chart-data/errors/', TrashbinCollectionReportErrorsPieChart.as_view(),
         name='collection_chart_data_errors'),
    path('collection/chart-data/fullness/', TrashbinCollectionReportFullnessPieChart.as_view(),
         name='collection_chart_data_fullness'),
    path('collection/chart-data/waste-types/', TrashbinCollectionReportWasteTypesPieChart.as_view(),
         name='collection_chart_data_waste_types'),
    path('collection/chart-data/sectors/', TrashbinCollectionReportSectorsPieChart.as_view(),
         name='collection_chart_data_sectors'),
], 'trashbin')

sensor_reports_urlpatterns = ([
    path('fullness/', sensor_report_fullness, name='fullness'),

apps/core/models.py
from django.conf import settings
from django.contrib.auth.validators import UnicodeUsernameValidator
from django.contrib.gis.db import models
from django.core.exceptions import ValidationError
from django.core.validators import MinValueValidator
from django.utils.translation import ugettext_lazy as _
from timezone_field import TimeZoneField


def validate_lang(value):
    if all(code != value for code, _ in settings.LANGUAGES):
        raise ValidationError(
            'There is no such language (%(lang)s), supported languages are: %(langs_list)s',
            params={'lang': value, 'langs_list': ', '.join((code for code, _ in settings.LANGUAGES))})


class Country(models.Model):
    name = models.CharField(
        max_length=128,
        verbose_name=_('title')
    )

    class Meta:
        verbose_name = _('country')
        verbose_name_plural = _('country')

    def __str__(self):
        return self.name


class City(models.Model):
    country = models.ForeignKey(
        to=Country,
        verbose_name=_('country'),
        on_delete=models.CASCADE,
    )
    title = models.CharField(
        verbose_name=_('title'),
        max_length=128,
    )

    class Meta:
        verbose_name = _('city')
        verbose_name_plural = _('cities')
        unique_together = ('country', 'title')
        ordering = ('title',)

    def __str__(self):
        return self.title


class Company(models.Model):
    name = models.CharField(
        max_length=128,
        verbose_name=_('title')
    )
    country = models.ForeignKey(
        to=Country,
        verbose_name=_('country'),
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
    )
    minsim = models.IntegerField(
        verbose_name=_('minimal SIM balance'),
        default=0
    )
    username_prefix = models.CharField(
        max_length=80,
        null=True,
        blank=True,
        unique=True,
        validators=[UnicodeUsernameValidator()],
    )
    timezone = TimeZoneField(default='UTC', display_GMT_offset=True, verbose_name=_('timezone'))
    lang = models.CharField(max_length=20, default='en', validators=[validate_lang])

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _('company')
        verbose_name_plural = _('companies')


class UsersToCompany(models.Model):
    ADMIN_ROLE = 'SA'
    OPERATOR_ROLE = 'OP'
    DRIVER_ROLE = 'DR'
    ROLES = (
        (ADMIN_ROLE, _('administrator')),
        (OPERATOR_ROLE, _('operator')),
        (DRIVER_ROLE, _('driver')),
    )
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        verbose_name=_('user'),
        related_name='user_to_company',
    )
    company = models.ForeignKey(
        Company,
        verbose_name=_('company'),
        on_delete=models.CASCADE,
    )
    role = models.CharField(
        verbose_name=_('role'),
        max_length=2,
        choices=ROLES,
        db_index=True,
    )
    timezone = TimeZoneField(null=True, blank=True, display_GMT_offset=True, verbose_name=_('timezone'))
    comment = models.CharField(_('comment'), max_length=150, blank=True)

    def __str__(self):
        return '%s (%s) %s' % (self.user, self.company, self.role)

    def is_driver(self):
        return self.role == UsersToCompany.DRIVER_ROLE

    def is_operator(self):
        return self.role == UsersToCompany.OPERATOR_ROLE

    def is_administrator(self):
        return self.role == UsersToCompany.ADMIN_ROLE


class FeatureFlag(models.Model):
    AIR_QUALITY = 'AIR_QUALITY'
    CHANGE_PASSWORD = 'CHANGE_PASSWORD'
    EFFICIENCY_MONITOR = 'EFFICIENCY_MONITOR'
    FULLNESS_FORECAST = 'FULLNESS_FORECAST'
    MOISTURE_DROP = 'MOISTURE_DROP'

    FEATURE_CHOICES = [
        (AIR_QUALITY, 'Air quality'),
        (CHANGE_PASSWORD, 'Change password'),
        (EFFICIENCY_MONITOR, 'Efficiency monitor'),
        (FULLNESS_FORECAST, 'Fullness forecast'),
        (MOISTURE_DROP, 'Drop moisture')
    ]

    FEATURE_DEFAULTS = {
        AIR_QUALITY: True,
        CHANGE_PASSWORD: True,
        EFFICIENCY_MONITOR: False,
        FULLNESS_FORECAST: False,
        MOISTURE_DROP: False,
    }

    feature = models.CharField(max_length=128, choices=FEATURE_CHOICES)
    company = models.ForeignKey(Company, related_name='features', on_delete=models.CASCADE)
    enabled = models.BooleanField(default=True)

    class Meta:
        unique_together = ('feature', 'company')

    def __str__(self):
        return '{} - {} - {}'.format(self.feature, self.company, self.enabled)


class Sectors(models.Model):
    name = models.CharField(max_length=200, verbose_name=_('title'))
    company = models.ForeignKey(Company, verbose_name=_('company'), null=True, on_delete=models.CASCADE)

    class Meta:
        verbose_name = _('sector')
        verbose_name_plural = _('sector')

    def __str__(self):
        return self.name

    @property
    def is_last_for_company(self):
        return len(self.company.sectors_set.all()) <= 1


class WasteType(models.Model):
    title = models.CharField(
        max_length=200,
        verbose_name=_('title')
    )
    code = models.CharField(
        max_length=8,
        db_index=True,
        verbose_name=_('waste code'),
        null=True,
    )
    # kg/liter
    density = models.FloatField(
        validators=[MinValueValidator(0.0)],
    )

    class Meta:
        verbose_name = _('waste type')
        verbose_name_plural = _('waste types')

    def __str__(self):
        return self.title

templates/routes/confirm_abort.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
    <h1 class="page_header">{% trans 'confirm route abort'|capfirst %}</h1>
    <p><strong>{{ object }}</strong></p>
    {% if aborting_not_supported_by_status %}
        <p>{% trans 'route_aborting_not_supported_by_status_warning' %}</p>
    {% endif %}
    <form action="{% url 'routes:abort' object.pk %}" method="post">
        {% csrf_token %}
        <button type="submit" {% if button_attrs %}{{ button_attrs }}{% endif %}>{% trans 'confirm'|capfirst %}</button>
    </form>
{% endblock %}

templates/routes/create.html
{% extends 'base.html' %}
{% load i18n static filters bootstrap3 %}


{% block content %}
    <div class="container" style='max-width:1020px; margin-bottom:100px'>
        <div id="vue-app-container">
            <h1 class="b-page-header">{% trans 'create routes'|capfirst %}</h1>

            <points :sectors="{{ sectors_json }}" inline-template>
                <div>
                    <section class="b-report-filter b-route-filter">
                        {% with points_templates_prefix|add:'/x-templates/filter.html' as template_name %}
                            {% include template_name %}
                        {% endwith %}
                    </section>
                    <section class="bordered stripped b-route-parameters">
                        {% with points_templates_prefix|add:'/x-templates/points.html' as template_name %}
                            {% include template_name %}
                        {% endwith %}
                    </section>
                </div>
            </points>

            <section class="bordered stripped b-route-parameters">
                <drivers :drivers="{{ drivers_json }}" :total-drivers-count="{{ total_drivers_count }}"></drivers>
            </section>

            {% verbatim %}
            <section class="bordered stripped b-route-parameters">
                <div class="b-route-parameters-row">
                    <h3 class="b-route-parameters-name">{% endverbatim %}
                        {% trans 'sectors'|capfirst %}
                        {% include 'info_buttons/sector.html' %}
                    {% verbatim %}</h3>
                    <div class="b-route-parameters-count">{% endverbatim %}{% trans 'sectors total'|capfirst %}{% verbatim %}: {{ sectors.length }}
                    </div>
                    <div class="b-route-parameters-comment">{% endverbatim %}{% trans 'choose sectors'|capfirst %}{% verbatim %}</div>
                    <div class="b-route-parameters-expand-container">
                        <button class="b-route-parameters-expand" v-on:click="setStep(2)" v-bind:class="{'selected-section' : isStep(2)}"></button>
                    </div>
                </div>

                <div v-show="isStep(2)">
                   <table class="b-route-table">
                        <tr>
                            <th>{% endverbatim %}{% trans 'drivers'|capfirst %}</th>
                            <th>{% trans 'sectors'|capfirst %}</th>{% verbatim %}
                        </tr>
                        <tr v-for="(driver, di) in orderedDrivers">
                            <td>{{ driver.username }}</td>
                            <td>
                                <a v-for="(sector, si) in orderedSectors"
                                   v-bind:class="{ 'active' : isActive(di, si), 'hidden' : isHidden(di, si) }"
                                   v-on:click="bindSector(di, si)"
                                   class="btn btn-default btn-xs b-route-button">{{ sector.name }}</a>
                            </td>
                        </tr>
                    </table>
                </div>
            </section>
            {% endverbatim %}
            <div v-if="sendFailed" class="alert alert-danger" role="alert">
                {% trans 'failed to send routes.'|capfirst %}
                {% trans 'please try again or contact our customer support service.'|capfirst %}
            </div>
            {% verbatim %}
            <button class="b-route-send" v-on:click="sendRoutes()" :disabled="!canSendRoutes">
                {% endverbatim %}{% trans 'start route'|capfirst %}{% verbatim %}
            </button>
            {% endverbatim %}
            <div class="clear-fix"></div>
        </div>

        <!-- Vue components templates -->
        <script id="drivers-template" type="text/x-template">
            {% include 'x-templates/drivers.html' %}
        </script>
    </div>
{% endblock %}


{% block js %}
    <script>
        var fullnessSelected = [
          {% for item in fullness %}
            {% array_value_of item 'title' 'fullness' True %}
          {% endfor %}
        ];
        var wasteTypesSelected = [
          {% for item in waste_types %}
            {% array_value_of item 'id' 'waste_type' %}
          {% endfor %}
        ];
        var errorTypesSelected = [
          {% for item in error_types %}
            {% array_value_of item 'id' 'error_type' %}
          {% endfor %}
        ];
        var sectorsSelected = [
          {% for item in sectors_list %}
            {% array_value_of item 'id' 'sector' %}
          {% endfor %}
        ];
        // Courtesy of this SO answer: https://stackoverflow.com/a/41303483/9335150
        var queryParamPairs = _.chain(window.location.search)
            .replace('?', '')
            .split('&')
            .map(_.partial(_.split, _, '=', 2));
        var mapBounds = _.pick(queryParamPairs.fromPairs().value(), ['north', 'east', 'south', 'west']);

        function isSerialPair(p) { return p[0] === 'serial'; }
        function takePairValue(p) { return p[1]; }

        var binSerials = _.chain(queryParamPairs).filter(isSerialPair).map(takePairValue).value();
        var yesStr = "{% trans 'yes'|capfirst %}";
        var noStr = "{% trans 'no'|capfirst %}";

        var fetchSensors = {{ fetch_sensors|lower }};
    </script>
    <script src="{% static 'js/route.js' %}"></script>
    <script>
        $(document).ready(function () {
            $('.b-route-filter-content').find('li').on('click', function () {
                $(this).toggleClass('selected');
                var input = $("#input_" + $(this).attr("id"));
                input.click();
            });
            $('.b-route-table--drivers-expand').on('click', function() {
                $(this).toggleClass('expanded');
            });
        });
    </script>
{% endblock %}


{% block title %}
    {% trans 'create routes'|capfirst %}
{% endblock %}


{% block extrahead %}
    <meta id="token" value="{{ csrf_token }}">
{% endblock %}

templates/routes/detail.html
{% extends 'base.html' %}
{% load i18n core_tags humanize %}

{% block content %}
    <div class="generic-detail-page">
        <h1>{% trans 'route details'|capfirst %}</h1>
        <h3><strong>{{ object }}</strong></h3>
        <div class="details-flex">
            <dl>
                <dt>{% trans 'driver'|capfirst %}</dt>
                <dd>{{ object.user.username }}</dd>
                <dt>{% trans 'route created'|capfirst %}</dt>
                <dd>{{ object.ctime|date:'SHORT_DATETIME_FORMAT' }}</dd>
                <dt>{% trans 'status'|capfirst %}</dt>
                <dd>{{ object.humanized_status }}</dd>
            </dl>
            {% if object.route_driver is not None %}
                <dl>
                    {% if object.route_driver.start_time %}
                        <dt>{% trans 'route started'|capfirst %}</dt>
                        <dd>{{ object.route_driver.start_time|date:'SHORT_DATETIME_FORMAT' }}</dd>
                    {% endif %}
                    {% if object.route_driver.finish_time %}
                        <dt>{% trans 'route finished'|capfirst %}</dt>
                        <dd>{{ object.route_driver.finish_time|date:'SHORT_DATETIME_FORMAT' }}</dd>
                    {% endif %}
                    {% if route_duration %}
                        <dt>{% trans 'route duration'|capfirst %}</dt>
                        <dd>{{ route_duration|smooth_timedelta }}</dd>
                    {% endif %}
                    {% if object.route_driver.track %}
                        <dt>{% trans 'track'|capfirst %}</dt>
                        <dd>{{ object.route_driver.track }}</dd>
                    {% endif %}
                    {% if object.route_driver.track_full %}
                        <dt>{% trans 'track_full'|capfirst %}</dt>
                        <dd>{{ object.route_driver.track_full }}</dd>
                    {% endif %}
                </dl>
            {% endif %}
        </div>
        <hr />
        <h2>{% trans 'route points'|capfirst %}</h2>
        <div class="tablediv">
            {% render_table_with_django2_compat points_table %}
            <div class="clear-fix"></div>
        </div>
        {% if can_be_resent %}
            <hr />
            <form action="{% url 'routes:resend' object.pk %}" method="post">
                {% csrf_token %}
                <button class="btn btn-primary" type="submit">{% trans 'resend route'|capfirst %}</button>
            </form>
        {% endif %}
    </div>
{% endblock %}

templates/routes/list.html
{% extends 'base.html' %}
{% load i18n core_tags messages %}

{% block content %}
    <h3>{% trans 'routes journal'|capfirst %}</h3>

    {% include '_alerts.html' %}

    <div class="tablediv">
        <a class="b-table-add" href="{% url 'routes:create' %}">{% trans 'create'|capfirst %}</a>
        {% render_table_with_django2_compat routes_table %}
    </div>
{% endblock %}